# Generated by Django 5.1.2 on 2024-12-01 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_examcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_table_pdf', models.FileField(blank=True, null=True, upload_to='time_tables/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='portal.examinationsession')),
            ],
        ),
    ]
