# Generated by Django 5.1.2 on 2024-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_examtimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='examtimetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
