# Generated by Django 5.1.2 on 2025-01-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, help_text='Examination year', null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year'], name='portal_stud_year_7fec02_idx'),
        ),
    ]
